export interface RoomData {
  id: string;
  propertyId: string;
  roomNumber: string;
  roomType: 'SINGLE' | 'DOUBLE' | 'TRIPLE' | 'FOUR_SHARING';
  sharingType: string;
  monthlyRent: number;
  securityDeposit: number;
  ac: boolean;
  attachedBathroom: boolean;
  balcony: boolean;
  available: boolean;
  totalBeds: number;
  occupiedBeds: number;
}

export interface AmenityData {
  id: string;
  name: string;
}

export interface PropertyData {
  id: string;
  ownerId: string;
  title: string;
  description: string;
  propertyType: 'PG' | 'FLAT' | 'HOSTEL' | 'CO_LIVING' | 'APARTMENT';
  address: string;
  locality: string;
  city: string;
  state: string;
  pincode: string;
  latitude: number;
  longitude: number;
  monthlyRentFrom: number;
  monthlyRentTo: number;
  securityDeposit: number;
  genderPreference: 'ANY' | 'MALE' | 'FEMALE';
  foodAvailable: boolean;
  furnished: 'FULLY' | 'SEMI' | 'UNFURNISHED';
  powerBackup: boolean;
  isVerified: boolean;
  verificationStatus: 'VERIFIED' | 'PENDING';
  trustScore: number;
  rating: number;
  reviewCount: number;
  occupancyRate: number;
  isDemoListing: boolean;
  dataSource: string;
  rooms: RoomData[];
  amenities: AmenityData[];
  owner: {
    id: string;
    name: string;
    email: string;
    phone: string;
    profileImage?: string;
    emailVerified: boolean;
    phoneVerified: boolean;
  };
}

export const INDIAN_CITIES_LIST = [
  'Mumbai', 'Bengaluru', 'Delhi NCR', 'Gurugram', 'Noida', 'Pune', 
  'Hyderabad', 'Chennai', 'Kolkata', 'Ahmedabad', 'Jaipur', 'Lucknow', 
  'Kochi', 'Indore', 'Chandigarh', 'Goa', 'Coimbatore', 'Bhopal'
];

export const MOCK_INDIAN_PROPERTIES: PropertyData[] = [
  // 1. MUMBAI
  {
    id: 'prop-mum-01',
    ownerId: 'owner-rajesh-mum',
    title: 'Urban Nest Co-Living Andheri',
    description: 'Luxury co-living space near Metro station in Andheri West. Fully furnished with high-speed WiFi, 3 meals daily, daily housekeeping, and 24/7 security.',
    propertyType: 'CO_LIVING',
    address: 'Plot 45, Veera Desai Road, Near Fun Republic Cinema',
    locality: 'Andheri West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400053',
    latitude: 19.1363,
    longitude: 72.8326,
    monthlyRentFrom: 14500,
    monthlyRentTo: 22000,
    securityDeposit: 29000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 96,
    rating: 4.8,
    reviewCount: 34,
    occupancyRate: 88.5,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-rajesh-mum',
      name: 'Rajesh Verma (Livora Verified Host)',
      email: 'owner@demo.livora.ai',
      phone: '+91 98123 45678',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a1', name: 'High-Speed WiFi' },
      { id: 'a2', name: 'AC' },
      { id: 'a3', name: '24/7 Power Backup' },
      { id: 'a4', name: '3-Meal Food Service' },
      { id: 'a5', name: 'Daily Housekeeping' },
      { id: 'a6', name: 'CCTV Security' },
      { id: 'a7', name: 'Washing Machine' },
      { id: 'a8', name: 'RO Water' },
    ],
    rooms: [
      {
        id: 'room-mum-101',
        propertyId: 'prop-mum-01',
        roomNumber: '101',
        roomType: 'SINGLE',
        sharingType: 'Private Single Occupancy',
        monthlyRent: 22000,
        securityDeposit: 44000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 1,
        occupiedBeds: 0,
      },
      {
        id: 'room-mum-102',
        propertyId: 'prop-mum-01',
        roomNumber: '102',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Twin Sharing',
        monthlyRent: 14500,
        securityDeposit: 29000,
        ac: true,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },
  {
    id: 'prop-mum-02',
    ownerId: 'owner-sunita-mum',
    title: 'Skyline Executive PG Powai',
    description: 'Premium working professional PG overlooking Powai Lake. Walking distance from IIT Bombay & Hiranandani Business Park.',
    propertyType: 'PG',
    address: 'Building 12, Hiranandani Gardens',
    locality: 'Powai',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400076',
    latitude: 19.1176,
    longitude: 72.9060,
    monthlyRentFrom: 16000,
    monthlyRentTo: 24000,
    securityDeposit: 32000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 94,
    rating: 4.7,
    reviewCount: 29,
    occupancyRate: 92.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-sunita-mum',
      name: 'Sunita Mehta',
      email: 'sunita.powai@livora.ai',
      phone: '+91 98222 33445',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a9', name: 'High-Speed WiFi' },
      { id: 'a10', name: 'AC' },
      { id: 'a11', name: 'Gym Access' },
      { id: 'a12', name: 'Biometric Access' },
      { id: 'a13', name: 'Food Included' },
      { id: 'a14', name: 'Lift' },
    ],
    rooms: [
      {
        id: 'room-mum-201',
        propertyId: 'prop-mum-02',
        roomNumber: '201',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Deluxe',
        monthlyRent: 16000,
        securityDeposit: 32000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },
  {
    id: 'prop-mum-03',
    ownerId: 'owner-vikram-mum',
    title: 'Bandra Coastal Co-Living',
    description: 'Chic sea-facing studio co-living flat near Carter Road, Bandra. Ideal for creators, techies & corporate executives.',
    propertyType: 'FLAT',
    address: 'Carter Road, Opposite Joggers Park',
    locality: 'Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400050',
    latitude: 19.0596,
    longitude: 72.8295,
    monthlyRentFrom: 25000,
    monthlyRentTo: 38000,
    securityDeposit: 50000,
    genderPreference: 'ANY',
    foodAvailable: false,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 98,
    rating: 4.9,
    reviewCount: 42,
    occupancyRate: 95.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-vikram-mum',
      name: 'Vikram Merchant',
      email: 'vikram.bandra@livora.ai',
      phone: '+91 99300 88776',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a15', name: 'Sea View' },
      { id: 'a16', name: 'High-Speed WiFi' },
      { id: 'a17', name: 'Smart TV' },
      { id: 'a18', name: 'Modular Kitchen' },
      { id: 'a19', name: 'Washing Machine' },
    ],
    rooms: [
      {
        id: 'room-mum-301',
        propertyId: 'prop-mum-03',
        roomNumber: '301',
        roomType: 'SINGLE',
        sharingType: 'Private Studio Flat',
        monthlyRent: 38000,
        securityDeposit: 76000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 1,
        occupiedBeds: 0,
      },
    ],
  },

  // 2. BENGALURU
  {
    id: 'prop-blr-01',
    ownerId: 'owner-anand-blr',
    title: 'Starlight Tech Hub Co-Living Koramangala',
    description: 'Premier co-living space in Koramangala 4th Block. Fast fiber internet, gaming zone, work lounge, organic meals, and startup community events.',
    propertyType: 'CO_LIVING',
    address: '80 Feet Road, 4th Block, Koramangala',
    locality: 'Koramangala',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560034',
    latitude: 12.9352,
    longitude: 77.6245,
    monthlyRentFrom: 12500,
    monthlyRentTo: 21000,
    securityDeposit: 25000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 97,
    rating: 4.8,
    reviewCount: 51,
    occupancyRate: 91.2,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-anand-blr',
      name: 'Anand Rao',
      email: 'anand.koramangala@livora.ai',
      phone: '+91 98450 11223',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a20', name: 'Gigabit WiFi' },
      { id: 'a21', name: 'Co-Working Lounge' },
      { id: 'a22', name: 'AC' },
      { id: 'a23', name: '24/7 Power Backup' },
      { id: 'a24', name: 'Buffet Meals' },
      { id: 'a25', name: 'PS5 Gaming Lounge' },
    ],
    rooms: [
      {
        id: 'room-blr-101',
        propertyId: 'prop-blr-01',
        roomNumber: 'K101',
        roomType: 'SINGLE',
        sharingType: 'Private Executive Room',
        monthlyRent: 21000,
        securityDeposit: 42000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 1,
        occupiedBeds: 0,
      },
      {
        id: 'room-blr-102',
        propertyId: 'prop-blr-01',
        roomNumber: 'K102',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Techie Room',
        monthlyRent: 12500,
        securityDeposit: 25000,
        ac: true,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },
  {
    id: 'prop-blr-02',
    ownerId: 'owner-kavitha-blr',
    title: 'Horizon Living HSR Layout',
    description: 'Spacious co-living space in HSR Sector 1 near BDA Complex. Quiet residential surroundings, high security, home-style North/South food.',
    propertyType: 'PG',
    address: '27th Main Road, Sector 1, HSR Layout',
    locality: 'HSR Layout',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560102',
    latitude: 12.9121,
    longitude: 77.6445,
    monthlyRentFrom: 11000,
    monthlyRentTo: 18500,
    securityDeposit: 22000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 93,
    rating: 4.6,
    reviewCount: 38,
    occupancyRate: 89.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-kavitha-blr',
      name: 'Kavitha Swamy',
      email: 'kavitha.hsr@livora.ai',
      phone: '+91 97400 33221',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a26', name: 'High-Speed WiFi' },
      { id: 'a27', name: 'North & South Indian Food' },
      { id: 'a28', name: 'Power Backup' },
      { id: 'a29', name: 'CCTV' },
      { id: 'a30', name: 'Terrace Garden' },
    ],
    rooms: [
      {
        id: 'room-blr-201',
        propertyId: 'prop-blr-02',
        roomNumber: 'H201',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 11000,
        securityDeposit: 22000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 2,
        occupiedBeds: 0,
      },
    ],
  },
  {
    id: 'prop-blr-03',
    ownerId: 'owner-suresh-blr',
    title: 'Silicon Valley PG Whitefield',
    description: 'Directly opposite ITPL Main Gate. Ideal for IT professionals working in ITPL, Brigade Tech Park, and EPIP Zone.',
    propertyType: 'HOSTEL',
    address: 'ITPL Main Road, Pattandur Agrahara',
    locality: 'Whitefield',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560066',
    latitude: 12.9863,
    longitude: 77.7380,
    monthlyRentFrom: 9500,
    monthlyRentTo: 16000,
    securityDeposit: 19000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'SEMI',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 91,
    rating: 4.5,
    reviewCount: 47,
    occupancyRate: 86.4,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-suresh-blr',
      name: 'Suresh Reddy',
      email: 'suresh.wf@livora.ai',
      phone: '+91 98860 99887',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a31', name: 'WiFi' },
      { id: 'a32', name: '3 Meals Daily' },
      { id: 'a33', name: 'Shuttle Service' },
      { id: 'a34', name: 'Power Backup' },
    ],
    rooms: [
      {
        id: 'room-blr-301',
        propertyId: 'prop-blr-03',
        roomNumber: 'W301',
        roomType: 'TRIPLE',
        sharingType: '3-Sharing Budget Room',
        monthlyRent: 9500,
        securityDeposit: 19000,
        ac: false,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 3,
        occupiedBeds: 1,
      },
    ],
  },

  // 3. DELHI NCR
  {
    id: 'prop-del-01',
    ownerId: 'owner-gupta-del',
    title: 'South Delhi Heritage Co-Living Saket',
    description: 'Chic modern co-living space near Saket Metro & Select Citywalk Mall. 24/7 power backup, high speed internet, gourmet food, zero brokerage.',
    propertyType: 'CO_LIVING',
    address: 'J-Block, Saket, Near PVR Anupam',
    locality: 'Saket',
    city: 'Delhi NCR',
    state: 'Delhi NCR',
    pincode: '110017',
    latitude: 28.5245,
    longitude: 77.2066,
    monthlyRentFrom: 13500,
    monthlyRentTo: 23000,
    securityDeposit: 27000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 95,
    rating: 4.7,
    reviewCount: 36,
    occupancyRate: 90.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-gupta-del',
      name: 'Ramesh Gupta',
      email: 'gupta.saket@livora.ai',
      phone: '+91 98110 55443',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a35', name: 'High-Speed WiFi' },
      { id: 'a36', name: 'Split AC' },
      { id: 'a37', name: '24/7 Power Backup' },
      { id: 'a38', name: 'Delicious Meals' },
      { id: 'a39', name: 'Housekeeping' },
    ],
    rooms: [
      {
        id: 'room-del-101',
        propertyId: 'prop-del-01',
        roomNumber: 'S101',
        roomType: 'SINGLE',
        sharingType: 'Private Single Room',
        monthlyRent: 23000,
        securityDeposit: 46000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 1,
        occupiedBeds: 0,
      },
      {
        id: 'room-del-102',
        propertyId: 'prop-del-01',
        roomNumber: 'S102',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 13500,
        securityDeposit: 27000,
        ac: true,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },
  {
    id: 'prop-del-02',
    ownerId: 'owner-neha-del',
    title: 'Hauz Khas Boho Student PG',
    description: 'Vibrant student & professional hostel near IIT Delhi & NIFT. Rooftop cafe vibe, laundry included, biometric access.',
    propertyType: 'HOSTEL',
    address: 'Hauz Khas Village Main Road',
    locality: 'Hauz Khas',
    city: 'Delhi NCR',
    state: 'Delhi NCR',
    pincode: '110016',
    latitude: 28.5494,
    longitude: 77.2001,
    monthlyRentFrom: 11500,
    monthlyRentTo: 19000,
    securityDeposit: 23000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 94,
    rating: 4.8,
    reviewCount: 40,
    occupancyRate: 93.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-neha-del',
      name: 'Neha Sharma',
      email: 'neha.hkv@livora.ai',
      phone: '+91 98711 22334',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a40', name: 'High-Speed WiFi' },
      { id: 'a41', name: 'Rooftop Lounge' },
      { id: 'a42', name: 'AC' },
      { id: 'a43', name: 'Laundry Service' },
    ],
    rooms: [
      {
        id: 'room-del-201',
        propertyId: 'prop-del-02',
        roomNumber: 'HK201',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 14000,
        securityDeposit: 28000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },

  // 4. GURUGRAM
  {
    id: 'prop-gur-01',
    ownerId: 'owner-kapoor-gur',
    title: 'Cyber City Executive Stay Sector 44',
    description: 'Luxury co-living space 5 minutes from Cyber City & HUDA City Centre Metro Station. Equipped with gym, gaming zone, and high-speed Wi-Fi.',
    propertyType: 'CO_LIVING',
    address: 'Plot 18, Sector 44, Near Fortis Hospital',
    locality: 'Sector 44',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122003',
    latitude: 28.4595,
    longitude: 77.0726,
    monthlyRentFrom: 15000,
    monthlyRentTo: 26000,
    securityDeposit: 30000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 98,
    rating: 4.9,
    reviewCount: 58,
    occupancyRate: 94.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-kapoor-gur',
      name: 'Sameer Kapoor',
      email: 'sameer.gurugram@livora.ai',
      phone: '+91 99100 44332',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a44', name: 'In-House Gym' },
      { id: 'a45', name: 'High-Speed WiFi' },
      { id: 'a46', name: 'Buffet Meals' },
      { id: 'a47', name: '24/7 Power Backup' },
      { id: 'a48', name: 'Covered Parking' },
    ],
    rooms: [
      {
        id: 'room-gur-101',
        propertyId: 'prop-gur-01',
        roomNumber: 'G101',
        roomType: 'SINGLE',
        sharingType: 'Private Executive Room',
        monthlyRent: 26000,
        securityDeposit: 52000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 1,
        occupiedBeds: 0,
      },
      {
        id: 'room-gur-102',
        propertyId: 'prop-gur-01',
        roomNumber: 'G102',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 15000,
        securityDeposit: 30000,
        ac: true,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },

  // 5. NOIDA
  {
    id: 'prop-noi-01',
    ownerId: 'owner-singh-noi',
    title: 'Noida Tech Hub PG Sector 62',
    description: 'Modern co-living space near Sector 62 Metro Station & Logix Cyber Park. Ideal for IT workers & university students.',
    propertyType: 'PG',
    address: 'B-Block, Sector 62, Near Electronic City Metro',
    locality: 'Sector 62',
    city: 'Noida',
    state: 'Uttar Pradesh',
    pincode: '201309',
    latitude: 28.6270,
    longitude: 77.3725,
    monthlyRentFrom: 8500,
    monthlyRentTo: 16000,
    securityDeposit: 17000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 92,
    rating: 4.6,
    reviewCount: 31,
    occupancyRate: 87.5,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-singh-noi',
      name: 'Virendra Singh',
      email: 'virendra.noida@livora.ai',
      phone: '+91 98180 77665',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a49', name: 'High-Speed WiFi' },
      { id: 'a50', name: 'AC' },
      { id: 'a51', name: 'Home Cooked Food' },
      { id: 'a52', name: '24/7 Power Backup' },
    ],
    rooms: [
      {
        id: 'room-noi-101',
        propertyId: 'prop-noi-01',
        roomNumber: 'N101',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 8500,
        securityDeposit: 17000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 2,
        occupiedBeds: 0,
      },
    ],
  },

  // 6. PUNE
  {
    id: 'prop-pun-01',
    ownerId: 'owner-pawar-pun',
    title: 'Pune Smart Co-Living Baner',
    description: 'High-tech co-living living space near Westend Mall, Baner. Fast internet, gym, power backup, zero brokerage.',
    propertyType: 'CO_LIVING',
    address: 'Baner Road, Near Sakal Nagar',
    locality: 'Baner',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411045',
    latitude: 18.5590,
    longitude: 73.7868,
    monthlyRentFrom: 9000,
    monthlyRentTo: 17500,
    securityDeposit: 18000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 95,
    rating: 4.7,
    reviewCount: 39,
    occupancyRate: 90.5,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-pawar-pun',
      name: 'Sachin Pawar',
      email: 'sachin.baner@livora.ai',
      phone: '+91 98230 44556',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a53', name: 'High-Speed WiFi' },
      { id: 'a54', name: 'AC' },
      { id: 'a55', name: 'Maharashtrian & North Meals' },
      { id: 'a56', name: '24/7 Power Backup' },
      { id: 'a57', name: 'Fitness Gym' },
    ],
    rooms: [
      {
        id: 'room-pun-101',
        propertyId: 'prop-pun-01',
        roomNumber: 'P101',
        roomType: 'SINGLE',
        sharingType: 'Private Deluxe Single',
        monthlyRent: 17500,
        securityDeposit: 35000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 1,
        occupiedBeds: 0,
      },
      {
        id: 'room-pun-102',
        propertyId: 'prop-pun-01',
        roomNumber: 'P102',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Twin Bed',
        monthlyRent: 9000,
        securityDeposit: 18000,
        ac: true,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },
  {
    id: 'prop-pun-02',
    ownerId: 'owner-kulkarni-pun',
    title: 'Hinjewadi Phase 1 Tech PG',
    description: 'Walking distance to Rajiv Gandhi Infotech Park Phase 1. Perfect for software developers & IT executives.',
    propertyType: 'PG',
    address: 'Hinjewadi Phase 1, Opposite Wipro Circle',
    locality: 'Hinjewadi',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411057',
    latitude: 18.5912,
    longitude: 73.7389,
    monthlyRentFrom: 8000,
    monthlyRentTo: 14500,
    securityDeposit: 16000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'SEMI',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 92,
    rating: 4.6,
    reviewCount: 33,
    occupancyRate: 88.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-kulkarni-pun',
      name: 'Nitin Kulkarni',
      email: 'nitin.hinjewadi@livora.ai',
      phone: '+91 97650 99881',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a58', name: 'High-Speed WiFi' },
      { id: 'a59', name: '3-Meal Food Service' },
      { id: 'a60', name: 'Power Backup' },
      { id: 'a61', name: 'CCTV' },
    ],
    rooms: [
      {
        id: 'room-pun-201',
        propertyId: 'prop-pun-02',
        roomNumber: 'HJ201',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 8000,
        securityDeposit: 16000,
        ac: false,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },

  // 7. HYDERABAD
  {
    id: 'prop-hyd-01',
    ownerId: 'owner-reddy-hyd',
    title: 'Cyberabad Co-Living Madhapur',
    description: 'Modern co-living space in Madhapur near Mindspace IT Park. Fully furnished, high-speed WiFi, South & North Indian cuisine.',
    propertyType: 'CO_LIVING',
    address: 'Plot 88, Kavuri Hills, Madhapur',
    locality: 'Madhapur',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500081',
    latitude: 17.4483,
    longitude: 78.3915,
    monthlyRentFrom: 9500,
    monthlyRentTo: 18000,
    securityDeposit: 19000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 96,
    rating: 4.8,
    reviewCount: 45,
    occupancyRate: 92.5,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-reddy-hyd',
      name: 'Venkat Reddy',
      email: 'venkat.madhapur@livora.ai',
      phone: '+91 98490 88776',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a62', name: 'High-Speed WiFi' },
      { id: 'a63', name: 'AC' },
      { id: 'a64', name: 'South & North Meals' },
      { id: 'a65', name: '24/7 Power Backup' },
      { id: 'a66', name: 'Gym' },
    ],
    rooms: [
      {
        id: 'room-hyd-101',
        propertyId: 'prop-hyd-01',
        roomNumber: 'M101',
        roomType: 'SINGLE',
        sharingType: 'Private Single Room',
        monthlyRent: 18000,
        securityDeposit: 36000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 1,
        occupiedBeds: 0,
      },
      {
        id: 'room-hyd-102',
        propertyId: 'prop-hyd-01',
        roomNumber: 'M102',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 9500,
        securityDeposit: 19000,
        ac: true,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },

  // 8. CHENNAI
  {
    id: 'prop-che-01',
    ownerId: 'owner-raman-che',
    title: 'OMR Tech Corridor Co-Living Velachery',
    description: 'Spacious co-living space near Velachery Railway Station & Taramani IT Corridor. Clean, peaceful, home food.',
    propertyType: 'CO_LIVING',
    address: '100 Feet Bypass Road, Velachery',
    locality: 'Velachery',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600042',
    latitude: 12.9782,
    longitude: 80.2206,
    monthlyRentFrom: 8000,
    monthlyRentTo: 15500,
    securityDeposit: 16000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 94,
    rating: 4.7,
    reviewCount: 32,
    occupancyRate: 88.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-raman-che',
      name: 'Subramanian Raman',
      email: 'raman.velachery@livora.ai',
      phone: '+91 98400 66554',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a67', name: 'High-Speed WiFi' },
      { id: 'a68', name: 'AC' },
      { id: 'a69', name: 'Traditional South Indian Food' },
      { id: 'a70', name: 'Power Backup' },
    ],
    rooms: [
      {
        id: 'room-che-101',
        propertyId: 'prop-che-01',
        roomNumber: 'V101',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 8000,
        securityDeposit: 16000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 2,
        occupiedBeds: 0,
      },
    ],
  },

  // 9. KOLKATA
  {
    id: 'prop-kol-01',
    ownerId: 'owner-banerjee-kol',
    title: 'Salt Lake Sector V IT Hub PG',
    description: 'Located right next to Wipro & TCS Delta Park in Salt Lake Sector V. Excellent food, 24/7 power backup, fast Wi-Fi.',
    propertyType: 'PG',
    address: 'Block EP & GP, Sector V, Salt Lake',
    locality: 'Salt Lake',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700091',
    latitude: 22.5726,
    longitude: 88.4331,
    monthlyRentFrom: 7000,
    monthlyRentTo: 14000,
    securityDeposit: 14000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 93,
    rating: 4.6,
    reviewCount: 28,
    occupancyRate: 87.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-banerjee-kol',
      name: 'Subhash Banerjee',
      email: 'banerjee.saltlake@livora.ai',
      phone: '+91 98300 22110',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a71', name: 'High-Speed WiFi' },
      { id: 'a72', name: 'AC' },
      { id: 'a73', name: 'Bengali & North Meals' },
      { id: 'a74', name: 'Power Backup' },
    ],
    rooms: [
      {
        id: 'room-kol-101',
        propertyId: 'prop-kol-01',
        roomNumber: 'SL101',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Twin Room',
        monthlyRent: 7000,
        securityDeposit: 14000,
        ac: true,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },

  // 10. AHMEDABAD
  {
    id: 'prop-ahm-01',
    ownerId: 'owner-patel-ahm',
    title: 'SG Highway Executive Co-Living',
    description: 'Modern co-living near Iscon Mega Mall & SG Highway. 100% vegetarian gourmet mess, high-speed WiFi, laundry.',
    propertyType: 'CO_LIVING',
    address: 'Near Iscon Cross Roads, SG Highway',
    locality: 'SG Highway',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380015',
    latitude: 23.0225,
    longitude: 72.5085,
    monthlyRentFrom: 7500,
    monthlyRentTo: 15000,
    securityDeposit: 15000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 94,
    rating: 4.7,
    reviewCount: 30,
    occupancyRate: 89.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-patel-ahm',
      name: 'Chirag Patel',
      email: 'chirag.sghighway@livora.ai',
      phone: '+91 98980 11223',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a75', name: 'High-Speed WiFi' },
      { id: 'a76', name: 'AC' },
      { id: 'a77', name: 'Pure Veg Kathiyawadi & North Food' },
      { id: 'a78', name: 'Power Backup' },
    ],
    rooms: [
      {
        id: 'room-ahm-101',
        propertyId: 'prop-ahm-01',
        roomNumber: 'SG101',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 7500,
        securityDeposit: 15000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 2,
        occupiedBeds: 0,
      },
    ],
  },

  // 11. JAIPUR
  {
    id: 'prop-jai-01',
    ownerId: 'owner-rathore-jai',
    title: 'Pink City Premium PG Malviya Nagar',
    description: 'Located in prime Malviya Nagar near World Trade Park. Clean, spacious rooms with AC, WiFi, and homelike Rajasthani meals.',
    propertyType: 'PG',
    address: 'Sector 4, Malviya Nagar, Near WTP',
    locality: 'Malviya Nagar',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302017',
    latitude: 26.8531,
    longitude: 75.8046,
    monthlyRentFrom: 6500,
    monthlyRentTo: 13000,
    securityDeposit: 13000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 92,
    rating: 4.6,
    reviewCount: 25,
    occupancyRate: 85.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-rathore-jai',
      name: 'Bhawani Singh Rathore',
      email: 'bhawani.jaipur@livora.ai',
      phone: '+91 94140 33221',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a79', name: 'High-Speed WiFi' },
      { id: 'a80', name: 'AC' },
      { id: 'a81', name: 'Delicious Meals' },
      { id: 'a82', name: 'RO Water' },
    ],
    rooms: [
      {
        id: 'room-jai-101',
        propertyId: 'prop-jai-01',
        roomNumber: 'MN101',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 6500,
        securityDeposit: 13000,
        ac: true,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },

  // 12. LUCKNOW
  {
    id: 'prop-luc-01',
    ownerId: 'owner-srivastava-luc',
    title: 'Gomti Nagar Executive Co-Living',
    description: 'Posh living space in Gomti Nagar near Wave Mall and IT City Lucknow. High-speed internet, power backup, tasty meals.',
    propertyType: 'CO_LIVING',
    address: 'Vipul Khand, Gomti Nagar',
    locality: 'Gomti Nagar',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    pincode: '226010',
    latitude: 26.8500,
    longitude: 80.9999,
    monthlyRentFrom: 6000,
    monthlyRentTo: 13500,
    securityDeposit: 12000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 93,
    rating: 4.7,
    reviewCount: 22,
    occupancyRate: 86.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-srivastava-luc',
      name: 'Alok Srivastava',
      email: 'alok.lucknow@livora.ai',
      phone: '+91 94150 99887',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a83', name: 'High-Speed WiFi' },
      { id: 'a84', name: 'AC' },
      { id: 'a85', name: 'Home Meals' },
      { id: 'a86', name: 'Power Backup' },
    ],
    rooms: [
      {
        id: 'room-luc-101',
        propertyId: 'prop-luc-01',
        roomNumber: 'GN101',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 6000,
        securityDeposit: 12000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 2,
        occupiedBeds: 0,
      },
    ],
  },

  // 13. KOCHI
  {
    id: 'prop-koc-01',
    ownerId: 'owner-menon-koc',
    title: 'Infopark Tech Co-Living Kakkanad',
    description: 'Modern co-living space walking distance from Infopark Kakkanad & SmartCity. Peaceful greenery, superfast Wi-Fi, Kerala home food.',
    propertyType: 'CO_LIVING',
    address: 'Infopark Expressway, Kakkanad',
    locality: 'Kakkanad',
    city: 'Kochi',
    state: 'Kerala',
    pincode: '682030',
    latitude: 10.0159,
    longitude: 76.3639,
    monthlyRentFrom: 7000,
    monthlyRentTo: 14500,
    securityDeposit: 14000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 94,
    rating: 4.8,
    reviewCount: 31,
    occupancyRate: 89.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-menon-koc',
      name: 'Unnikrishnan Menon',
      email: 'menon.kochi@livora.ai',
      phone: '+91 94470 12345',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a87', name: 'High-Speed WiFi' },
      { id: 'a88', name: 'AC' },
      { id: 'a89', name: 'Kerala Homestyle Meals' },
      { id: 'a90', name: '24/7 Power Backup' },
    ],
    rooms: [
      {
        id: 'room-koc-101',
        propertyId: 'prop-koc-01',
        roomNumber: 'K101',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 7000,
        securityDeposit: 14000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },

  // 14. INDORE
  {
    id: 'prop-ind-01',
    ownerId: 'owner-sharma-ind',
    title: 'Indore Clean City Co-Living Vijay Nagar',
    description: 'Cleanest co-living space in Vijay Nagar near C21 Mall. Perfect for students and working professionals.',
    propertyType: 'PG',
    address: 'Scheme 54, Vijay Nagar',
    locality: 'Vijay Nagar',
    city: 'Indore',
    state: 'Madhya Pradesh',
    pincode: '452010',
    latitude: 22.7533,
    longitude: 75.8937,
    monthlyRentFrom: 6000,
    monthlyRentTo: 12500,
    securityDeposit: 12000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 93,
    rating: 4.7,
    reviewCount: 26,
    occupancyRate: 88.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-sharma-ind',
      name: 'Rakesh Sharma',
      email: 'rakesh.indore@livora.ai',
      phone: '+91 98260 55443',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a91', name: 'High-Speed WiFi' },
      { id: 'a92', name: 'AC' },
      { id: 'a93', name: 'Indori Food & Mess' },
      { id: 'a94', name: 'Power Backup' },
    ],
    rooms: [
      {
        id: 'room-ind-101',
        propertyId: 'prop-ind-01',
        roomNumber: 'IN101',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 6000,
        securityDeposit: 12000,
        ac: true,
        attachedBathroom: true,
        balcony: false,
        available: true,
        totalBeds: 2,
        occupiedBeds: 0,
      },
    ],
  },

  // 15. CHANDIGARH
  {
    id: 'prop-cha-01',
    ownerId: 'owner-singh-cha',
    title: 'City Beautiful Co-Living Sector 17',
    description: 'Premium co-living space in Sector 17, Chandigarh. Lush green surrounding, high-speed WiFi, gym access.',
    propertyType: 'CO_LIVING',
    address: 'Sector 17-C, Near Parade Ground',
    locality: 'Sector 17',
    city: 'Chandigarh',
    state: 'Chandigarh',
    pincode: '160017',
    latitude: 30.7333,
    longitude: 76.7794,
    monthlyRentFrom: 8000,
    monthlyRentTo: 16500,
    securityDeposit: 16000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 95,
    rating: 4.8,
    reviewCount: 34,
    occupancyRate: 90.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-singh-cha',
      name: 'Gurpreet Singh',
      email: 'gurpreet.chandigarh@livora.ai',
      phone: '+91 98140 11223',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a95', name: 'High-Speed WiFi' },
      { id: 'a96', name: 'AC' },
      { id: 'a97', name: 'Punjabi Homestyle Food' },
      { id: 'a98', name: 'Power Backup' },
    ],
    rooms: [
      {
        id: 'room-cha-101',
        propertyId: 'prop-cha-01',
        roomNumber: 'CH101',
        roomType: 'DOUBLE',
        sharingType: '2-Sharing Room',
        monthlyRent: 8000,
        securityDeposit: 16000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 2,
        occupiedBeds: 1,
      },
    ],
  },

  // 16. GOA
  {
    id: 'prop-goa-01',
    ownerId: 'owner-dza-goa',
    title: 'Coastal Bay Workation Co-Living Panaji',
    description: 'Workation-focused co-living space in Panaji, Goa. Fast optical Wi-Fi, power backup, rooftop lounge, close to Miramar Beach.',
    propertyType: 'CO_LIVING',
    address: 'Miramar Beach Road, Panaji',
    locality: 'Panaji',
    city: 'Goa',
    state: 'Goa',
    pincode: '403001',
    latitude: 15.4909,
    longitude: 73.8278,
    monthlyRentFrom: 12000,
    monthlyRentTo: 22000,
    securityDeposit: 24000,
    genderPreference: 'ANY',
    foodAvailable: true,
    furnished: 'FULLY',
    powerBackup: true,
    isVerified: true,
    verificationStatus: 'VERIFIED',
    trustScore: 97,
    rating: 4.9,
    reviewCount: 49,
    occupancyRate: 92.0,
    isDemoListing: true,
    dataSource: 'ALL_INDIA_VERIFIED',
    owner: {
      id: 'owner-dza-goa',
      name: 'Antonio D’Souza',
      email: 'antonio.goa@livora.ai',
      phone: '+91 98221 77889',
      emailVerified: true,
      phoneVerified: true,
    },
    amenities: [
      { id: 'a99', name: 'High-Speed Optical WiFi' },
      { id: 'a100', name: 'Rooftop Workstation' },
      { id: 'a101', name: 'AC' },
      { id: 'a102', name: 'Power Backup' },
    ],
    rooms: [
      {
        id: 'room-goa-101',
        propertyId: 'prop-goa-01',
        roomNumber: 'G101',
        roomType: 'SINGLE',
        sharingType: 'Private Workation Suite',
        monthlyRent: 22000,
        securityDeposit: 44000,
        ac: true,
        attachedBathroom: true,
        balcony: true,
        available: true,
        totalBeds: 1,
        occupiedBeds: 0,
      },
    ],
  },
];

/**
 * Filter properties based on user search parameters
 */
export function filterIndianProperties(params: {
  city?: string;
  locality?: string;
  propertyType?: string;
  maxRent?: number;
  minRent?: number;
  ac?: string | boolean;
  food?: string | boolean;
  powerBackup?: string | boolean;
  verified?: string | boolean;
}) {
  let list = [...MOCK_INDIAN_PROPERTIES];

  if (params.city && params.city.trim() !== '') {
    const qCity = params.city.trim().toLowerCase();
    list = list.filter((p) => {
      const pCity = p.city.toLowerCase();
      const pState = p.state.toLowerCase();
      // Flexible matching for Delhi / Delhi NCR / Bangalore / Bengaluru / etc.
      if (qCity === 'delhi' || qCity === 'delhi ncr') {
        return pCity.includes('delhi') || pCity.includes('gurugram') || pCity.includes('noida');
      }
      if (qCity === 'bangalore' || qCity === 'bengaluru' || qCity === 'blr') {
        return pCity.includes('bengaluru') || pCity.includes('bangalore');
      }
      return pCity.includes(qCity) || pState.includes(qCity);
    });
  }

  if (params.locality && params.locality.trim() !== '') {
    const qLoc = params.locality.trim().toLowerCase();
    list = list.filter((p) => p.locality.toLowerCase().includes(qLoc) || p.address.toLowerCase().includes(qLoc));
  }

  if (params.propertyType && params.propertyType.trim() !== '') {
    list = list.filter((p) => p.propertyType === params.propertyType);
  }

  if (params.maxRent && params.maxRent > 0) {
    list = list.filter((p) => p.monthlyRentFrom <= params.maxRent!);
  }

  if (params.minRent && params.minRent > 0) {
    list = list.filter((p) => p.monthlyRentFrom >= params.minRent!);
  }

  if (params.ac === 'true' || params.ac === true) {
    list = list.filter((p) => p.rooms.some((r) => r.ac));
  }

  if (params.food === 'true' || params.food === true) {
    list = list.filter((p) => p.foodAvailable);
  }

  if (params.powerBackup === 'true' || params.powerBackup === true) {
    list = list.filter((p) => p.powerBackup);
  }

  if (params.verified === 'true' || params.verified === true) {
    list = list.filter((p) => p.isVerified || p.verificationStatus === 'VERIFIED');
  }

  return list;
}
